[2021-02-23 14:56:36,288] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:41,275] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-23 14:56:41,284] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:41,296] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-23 14:56:41,322] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:56:44,049] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): also_run_this> on 2021-02-21T00:00:00+00:00
[2021-02-23 14:56:44,535] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2021-02-21T00:00:00+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpj7xgkc9h', '--error-file', '/tmp/tmpg3b3yt9y']
[2021-02-23 14:56:44,537] {standard_task_runner.py:77} INFO - Job 15: Subtask also_run_this
[2021-02-23 14:56:44,593] {standard_task_runner.py:52} INFO - Started process 72 to run task
[2021-02-23 14:56:46,369] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.also_run_this 2021-02-21T00:00:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:56:48,194] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-02-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-21T00:00:00+00:00
[2021-02-23 14:56:48,246] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-23 14:56:48,330] {bash.py:158} INFO - Running command: echo "run_id=scheduled__2021-02-21T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-02-21 00:00:00+00:00: scheduled__2021-02-21T00:00:00+00:00, externally triggered: False>"
[2021-02-23 14:56:48,823] {bash.py:169} INFO - Output:
[2021-02-23 14:56:48,912] {bash.py:173} INFO - run_id=scheduled__2021-02-21T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-02-21 00:00:00+00:00: scheduled__2021-02-21T00:00:00+00:00, externally triggered: False>
[2021-02-23 14:56:48,994] {bash.py:177} INFO - Command exited with return code 0
[2021-02-23 14:56:49,836] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20210221T000000, start_date=20210223T145636, end_date=20210223T145649
[2021-02-23 14:56:51,017] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-23 14:56:51,049] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 72
[2021-02-23 14:56:51,059] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-23 14:56:51,083] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-23 14:56:51,499] {process_utils.py:66} INFO - Process psutil.Process(pid=72, status='terminated', exitcode=1, started='14:56:43') (72) terminated with exit code 1
