[2021-02-23 14:57:13,753] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: tutorial.print_date 2015-06-01T00:00:00+00:00 [queued]>
[2021-02-23 14:57:15,354] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: tutorial.print_date 2015-06-01T00:00:00+00:00 [queued]>
[2021-02-23 14:57:15,363] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:57:15,414] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-02-23 14:57:15,423] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:57:16,150] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): print_date> on 2015-06-01T00:00:00+00:00
[2021-02-23 14:57:16,270] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2021-02-23 14:57:16,612] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial', 'print_date', '2015-06-01T00:00:00+00:00', '--job-id', '31', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/tutorial.py', '--cfg-path', '/tmp/tmp5nvya_8a', '--error-file', '/tmp/tmpcxbrj71d']
[2021-02-23 14:57:16,654] {standard_task_runner.py:77} INFO - Job 31: Subtask print_date
[2021-02-23 14:57:19,082] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial.print_date 2015-06-01T00:00:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:57:19,983] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2015-06-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-06-01T00:00:00+00:00
[2021-02-23 14:57:19,997] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-02-23 14:57:20,010] {bash.py:158} INFO - Running command: date
[2021-02-23 14:57:20,188] {bash.py:169} INFO - Output:
[2021-02-23 14:57:20,208] {bash.py:173} INFO - Tue Feb 23 14:57:20 UTC 2021
[2021-02-23 14:57:20,211] {bash.py:177} INFO - Command exited with return code 0
[2021-02-23 14:57:20,698] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=print_date, execution_date=20150601T000000, start_date=20210223T145713, end_date=20210223T145720
[2021-02-23 14:57:21,880] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-23 14:57:21,888] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 109
[2021-02-23 14:57:21,913] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-23 14:57:21,915] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2021-02-23 14:57:22,031] {process_utils.py:66} INFO - Process psutil.Process(pid=109, status='terminated', exitcode=1, started='14:57:15') (109) terminated with exit code 1
