[2021-02-23 14:59:14,550] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_passing_params_via_test_command.run_this 2021-02-22T00:15:00+00:00 [queued]>
[2021-02-23 14:59:14,859] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_passing_params_via_test_command.run_this 2021-02-22T00:15:00+00:00 [queued]>
[2021-02-23 14:59:14,900] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:59:14,904] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-23 14:59:14,914] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-23 14:59:15,226] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): run_this> on 2021-02-22T00:15:00+00:00
[2021-02-23 14:59:15,369] {standard_task_runner.py:52} INFO - Started process 300 to run task
[2021-02-23 14:59:15,649] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_passing_params_via_test_command', 'run_this', '2021-02-22T00:15:00+00:00', '--job-id', '114', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_passing_params_via_test_command.py', '--cfg-path', '/tmp/tmpme4am8i4', '--error-file', '/tmp/tmp3e0ppmdj']
[2021-02-23 14:59:15,737] {standard_task_runner.py:77} INFO - Job 114: Subtask run_this
[2021-02-23 14:59:17,599] {logging_mixin.py:104} INFO - Running <TaskInstance: example_passing_params_via_test_command.run_this 2021-02-22T00:15:00+00:00 [running]> on host 0513e3a4eab6
[2021-02-23 14:59:18,396] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_passing_params_via_test_command
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-02-22T00:15:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-22T00:15:00+00:00
[2021-02-23 14:59:18,411] {logging_mixin.py:104} INFO -  'miff' was passed in via task params = agg
[2021-02-23 14:59:18,453] {python.py:118} INFO - Done. Returned value was: 1
[2021-02-23 14:59:18,617] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_passing_params_via_test_command, task_id=run_this, execution_date=20210222T001500, start_date=20210223T145914, end_date=20210223T145918
[2021-02-23 14:59:22,166] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-02-23 14:59:22,212] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-23 14:59:22,511] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 300
[2021-02-23 14:59:22,603] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-23 14:59:23,425] {process_utils.py:66} INFO - Process psutil.Process(pid=300, status='terminated', exitcode=1, started='14:59:14') (300) terminated with exit code 1
